### ISSUE TITLE
Job Center/City Services

### ISSUE THREAD

**Issue by Tengri2270** [Jigara/OGN-Roleplay#10]
Please also take a look at the City Services building whenever you have the time as it doesn't have any prompt in front of it in order for us to enter it. We will need that in order to test all the jobs and to get enough police on the city to also test some of the criminal activity.

![a](https://user-images.githubusercontent.com/83185289/116826036-e8feb880-ab46-11eb-85eb-cbe651e66d7b.PNG)
![Capture](https://user-images.githubusercontent.com/83185289/116826038-e9974f00-ab46-11eb-9643-ba8d1620b664.PNG)

Tengri,
OGN Team

**Comment by Jigara** [comment]
Hey,

- City Services Menu is now accessible.
- New proper coordinates have been configured:
![image](https://user-images.githubusercontent.com/79502719/116826501-42c0ac00-ab62-11eb-9c7b-a3d8324205cf.png)

Thank you,
Team OGN.
