### ISSUE TITLE
Gun Shop

### ISSUE THREAD

**Issue by Tengri2270** [Jigara/OGN-Roleplay#11]
Whenever you have the time please also check the Gun Shop.
-at the moment it has no actual firearms or ammo to buy 
-we would also need the gun license if it is not available at a new location

Tengri,
OGN Team

**Comment by Jigara** [comment]
Hello,

Could you please follow up with a recommended list of firearms to be configured, along with balanced prices.

Thank you,
Team OGN.

**Comment by Tengri2270** [comment]
So, for the basic guns in the gun-shop I think these will be a perfect addition along with Pistol ammo, I don't think we should add any other weapons than pistols at the moment.

-the SNS Pistol (weapon_snspistol) 1000$
-The Walther P99 (weapon_pistol) 1500 $
-The Heavy Pistol (weapon_heavypistol) 2500$
-Pistol Ammo x1 50$

![image](https://user-images.githubusercontent.com/83185289/116919248-d6978400-ac05-11eb-8619-7560698d84fa.png)

**Comment by Jigara** [comment]
**Implemented as of [5/4/2021].**

Please double check in-game.
       /\
Thank you,
Team OGN.
