### ISSUE TITLE
Police Job 

### ISSUE THREAD

**Issue by Tengri2270** [Jigara/OGN-Roleplay#12]
Good day, This will include all the functions that we've found from the police that work and do not work.

For the Police Department location ,only if you have the police job , you can unlock any areas (armory, lockers, jail) and you can start duty by going at the PC in the lobby.
If you are the Police Chief (rank 4) you can also access the boss menu, which let's you hire, promote people and also let's you deposit money for the police.
At the Police Department at the moment from what I can see the only thing that is missing is either a system for the police outfits, or adding all the police uniforms to the clothing store so we can change them there.
-The armory has weapons and police equipment inside and can be accessed by any people in the Police Department. 

Radial Work menu for Police.
-The "take license" option does not seem to work 
-From Police interaction , the jail function doesn't seem to work ,it says that it jails the person but it doesn't , I will try with higher amounts of time also)
-The Emergency button we do not know what it does
-Check tune status i do not believe it's available (it says NULL: Chiptuned:no)
-Reset house key I do not know what it does
Apart from those, the rest seem to work just fine.
-Cuffing a player, either by /cuff or using the radial menu.
-Search a player 
-Escort a player 
-You can place down several types of objects including spike strips which work

The pings for Police work, if someone is driving recklessly or shoots a weapon you receive a message in the top right of the screen with a description of the suspect and relative location. :D

![image](https://user-images.githubusercontent.com/83185289/117019733-8cb4a980-acaa-11eb-906c-0764683fb917.png)
![image](https://user-images.githubusercontent.com/83185289/117020080-f1700400-acaa-11eb-8b98-7883f5ad2935.png)

Tengri,
OGN TEAM.

**Comment by BIBZ1231** [comment]
Reset House Key is used after a robbery to lock the house. 
Chiptuned should be no unless the car is tuned which is irrelevant unless you intend on making tunerchips illegal, which is also great RP and much of a change from bank robbery after bank robbery with the same outcome over and over.
I personally have not looked at the jail script, but there are numerous options if the one in the current framework does not work properly or needs a complete rewrite.

**Comment by BIBZ1231** [comment]
-----------------qb-ambulance--config.lua---lines---1to53----for gabz_pillbox_hospital-------------
Config = {}          

Config.MinimalDoctors = 2    -----Not sure why?

Config.Locations = {
    ["Self check-in"] = {x = 309.08, y = -592.91, z = 43.28, h = 0.0},
    ["duty"] = {
        [1] = {x = 311.22, y = -597.37, z = 43.28, h = 0.0},   ---pillbox main floor in lockeroom behind recep desk
        [2] = {x = -254.88, y = 6324.5, z = 32.58, h = 0.0},
    },    
    ["vehicle"] = {
        [1] = {x = 294.578, y = -574.761, z = 43.179, h = 35.792},  ---Downstairs using elevetor down to garage
        [2] = {x = -234.28, y = 6329.16, z = 32.15, h = 222.5},
    },
    ["helicopter"] = {
        [1] = {x = 351.58, y = -587.45, z = 74.16, h = 160.5},     ----pillbox 
        [2] = {x = -475.43, y = 5988.353, z = 31.716, h = 31.34},
    },    
    ["armory"] = {
        [1] = {x = 306.26, y = -601.7, z = 43.28, h = 90.654},  -----pillbox
        [2] = {x = -245.13, y = 6315.71, z = 32.82, h = 90.654},
    },
    ["roof"] = {
        [1] = {x = 338.5, y = -583.85, z = 74.16, h = 245.5},   -----elevator from roof to main
    },
    ["main"] = {
        [1] = {x = 332.51, y = -595.74, z = 43.28, h = 76.0},  ----elevator from main going up to roof
    },
    ["maindown"] = {
        [1] = {x = 330.64, y = -600.75, z = 43.28, h = 68.67},  ----elevator from main going down
    },	
    ["garageup"] = {                                                             
        [1] = {x = 340.89, y = -580.78, z = 28.28, h = 65.06}, ----elevator from garage going up
    },
	["garage"] = {
        [1] = {x = 332.57, y = -584.41, z = 28.8, h = 80.06},   ----getting out of elevator in garage from main
    },	
    ["beds"] = {
        [1] = {x = 311.13, y = -582.89, z = 43.53, h = 335.65, taken = false, model = 1631638868},
        [2] = {x = 313.96, y = -579.05, z = 43.53, h = 164.5, taken = false, model = 1631638868},
        [3] = {x = 314.58, y = -584.09, z = 43.53, h = 335.65, taken = false, model = 1631638868},
        [4] = {x = 317.74, y = -585.29, z = 43.53, h = 335.65, taken = false, model = 1631638868},
        [5] = {x = 319.47, y = -581.04, z = 43.53, h = 164.5, taken = false, model = 1631638868}, 
        [6] = {x = 366.43, y = -581.54, z = 43.28, h = 66.5, taken = false, model = 1631638868}, 
        [7] = {x = 364.93, y = -585.86, z = 43.28, h = 67.5, taken = false, model = 1631638868}, 
        [8] = {x = 363.82, y = -589.09, z = 43.28, h = 68.5, taken = false, model = 1631638868},
    }
}
Config.Vehicles = {
    ["ambulance22"] = "Ambulance",   -----------------breakems---------------------------Bibz has these----------------
    ["lsambulance"] = "Mini-Van",       ----------------breakems2 ----not the nicest looking but no memory errors-------
	["ems"] = "EMS Car",              ------------------breakems3--------------Jay Tapp can reskin them if needed---------
}

**Comment by BIBZ1231** [comment]
------------Line117to214---in--qb-ambulancejob----client---job.lua---elevators----
            local currentHospital = 1

            for k, v in pairs(Config.Locations["main"]) do
                local dist = #(pos - vector3(v.x, v.y, v.z))
                if dist < 1.5 then
                    DrawText3D(v.x, v.y, v.z, "~g~E~w~ - Take the elevator to the roof")
                    if IsControlJustReleased(0, 38) then
                        DoScreenFadeOut(500)
                        while not IsScreenFadedOut() do
                            Citizen.Wait(10)
                        end

                        currentHospital = k

                        local coords = Config.Locations["roof"][currentHospital]
                        SetEntityCoords(ped, coords.x, coords.y, coords.z, 0, 0, 0, false)
                        SetEntityHeading(ped, coords.h)

                        Citizen.Wait(100)

                        DoScreenFadeIn(1000)
                    end
                end
            end
			
			for k, v in pairs(Config.Locations["maindown"]) do
                local dist = #(pos - vector3(v.x, v.y, v.z))
                if dist < 1.5 then
                    DrawText3D(v.x, v.y, v.z, "~g~E~w~ - Take the elevator up")
                    if IsControlJustReleased(0, 38) then
                        DoScreenFadeOut(500)
                        while not IsScreenFadedOut() do
                            Citizen.Wait(10)
                        end

                        currentHospital = k

                        local coords = Config.Locations["garage"][currentHospital]
                        SetEntityCoords(ped, coords.x, coords.y, coords.z, 0, 0, 0, false)
                        SetEntityHeading(ped, coords.h)

                        Citizen.Wait(100)

                        DoScreenFadeIn(1000)
                    end
                end
            end
			
			for k, v in pairs(Config.Locations["garageup"]) do
                local dist = #(pos - vector3(v.x, v.y, v.z))
                if dist < 1.5 then
                    DrawText3D(v.x, v.y, v.z, "~g~E~w~ - Take the elevator down")
                    if IsControlJustReleased(0, 38) then
                        DoScreenFadeOut(500)
                        while not IsScreenFadedOut() do
                            Citizen.Wait(10)
                        end

                        currentHospital = k

                        local coords = Config.Locations["main"][currentHospital]
                        SetEntityCoords(ped, coords.x, coords.y, coords.z, 0, 0, 0, false)
                        SetEntityHeading(ped, coords.h)

                        Citizen.Wait(100)

                        DoScreenFadeIn(1000)
                    end
                end
            end

            for k, v in pairs(Config.Locations["roof"]) do
                local dist = #(pos - vector3(v.x, v.y, v.z))
                if dist < 1.5 then
                    DrawText3D(v.x, v.y, v.z, "~g~E~w~ - Take the elevator down")
                    if IsControlJustReleased(0, 38) then
                        DoScreenFadeOut(500)
                        while not IsScreenFadedOut() do
                            Citizen.Wait(10)
                        end

                        currentHospital = k

                        local coords = Config.Locations["main"][currentHospital]
                        SetEntityCoords(ped, coords.x, coords.y, coords.z, 0, 0, 0, false)
                        SetEntityHeading(ped, coords.h)

                        Citizen.Wait(100)

                        DoScreenFadeIn(1000)
                    end
                end
            end
        else
            Citizen.Wait(1000)
        end
    end
end)
